### ISSUE TITLE
Create sidebar with object and service elements

### ISSUE THREAD

**Issue by SigmundGranaas** [aclgen/aclgen_frontend#9]
## Description
Object and service elements needs to be organized into the sidebar of the application. The sidebar will contain the following information:
- All devices and availible environments
- All possbile services
- All possible Network objects

### TODO
- [ ] Create a functional sidebar with to distinctive elements, one with devices, and one with services and objects
- [ ] Create a folder structure for all elements
- [ ] Wire all elements to Redux
- [ ] Create endpoints for fetching objects, services and devices

Estimate: 4hrs
